### ISSUE TITLE
Possible issue with pumpkin growth

### ISSUE THREAD

**Issue by linaritara** [VinterNacht/FieldsOfGold#8]
Planted two pumpkin plants, both had green pumpkins growing by stage 2, harvestable pumpkins by stage 3. This seemed abnormally fast to me, but perhaps more importantly the plants haven't produced any new pumpkins since then - just a series of single vines that wither within an ingame day or two after growing.

**Comment by VinterNacht** [comment]
Will be working on getting this sorted, won't be out in today's release, but very soon.

**Comment by VinterNacht** [comment]
Pumpkin Growth Issue Resolved (?)
