### ISSUE TITLE
critical firepit bug

### ISSUE THREAD

**Issue by cyraxan** [VinterNacht/FieldsOfGold#9]
it is impossible to make a new firepit with FoG 1.1.15&1.2.0
nothing happens when you press shift+RMB dry grass, but ctrl+shift+RMB starts haystack

**Comment by VinterNacht** [comment]
YIKES...  Will get a patch out ASAP.

**Comment by VinterNacht** [comment]
Fixed in next release, will be out sometime today.

**Comment by VinterNacht** [comment]
Bug Eliminated
